export const GET_CITIES_WITH_PREFIX = 'GET_CITIES_WITH_PREFIX';
export const GET_CITIES_WITH_PREFIX_SUCCESS = 'GET_CITIES_WITH_PREFIX_SUCCESS';
export const ADD_CITY_AS_FAV = 'ADD_CITY_AS_FAV';
export const REMOVE_CITY_FROM_FAV = 'REMOVE_CITY_FROM_FAV';
export const GET_WEATHER_FOR_CITY = 'GET_WEATHER_FOR_CITY';
export const GET_WEATHER_FOR_CITY_SUCCESS = 'GET_WEATHER_FOR_CITY_SUCCESS';
export const HANDLE_API_ERROR = 'HANDLE_API_ERROR';
export const CLEAR_API_ERROR = 'CLEAR_API_ERROR';
